routes/web.php
<?php

use App\Http\Controllers\Auth;
use App\Http\Controllers\User;
use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\SettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middle-ware group. Now create something great!
|
*/

if (application_installed()) {
    Route::get('/install/final', function () {
        return redirect('/');
    });
}

// Handle Main / Route

// Authenticates Routes
Route::middleware([])->group(function () {
    Route::get('/locale', [PublicController::class, 'set_lang'])->name('language');

    // Authenticates Routes
    Route::get('/auth/{service}', [Auth\SocialAuthController::class, 'redirect'])->name('social.login');
    Route::get('/auth/{service}/callback', [Auth\SocialAuthController::class, 'callback'])->name('social.login.callback');
    Route::post('/auth/social/register', [Auth\SocialAuthController::class, 'register'])->name('social.register');
    Auth::routes();
    Route::get('/', [Auth\LoginController::class, 'checkLoginState'])->name('home');
    Route::get('verify/', [Auth\VerifyController::class, 'index'])->name('verify');
    Route::get('verify/resend', [Auth\VerifyController::class, 'resend'])->name('verify.resend');
    Route::get('verify/{id}/{token}', [Auth\VerifyController::class, 'verify'])->name('verify.email');
    Route::get('verify/success', [Auth\LoginController::class, 'verified'])->name('verified');
    Route::get('register/success', [Auth\LoginController::class, 'registered'])->name('registered');
    Route::any('log-out', [Auth\LoginController::class, 'logout'])->name('log-out');
    // Google 2FA Routes
    Route::get('/login/2fa', [Auth\SocialAuthController::class, 'show_2fa_form'])->middleware('auth')->name('auth.2fa');
    Route::get('/login/2fa/reset', [Auth\SocialAuthController::class, 'show_2fa_reset_form'])->name('auth.2fa.reset');
    Route::post('/login/2fa/reset', [Auth\SocialAuthController::class, 'reset_2fa']);
    Route::post('/login/2fa', function () {
        return redirect()->route('home');
    })->middleware(['auth', 'g2fa']);

    // if(is_maintenance()){
    Route::get('admin/login', [Auth\LoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('admin/login', [Auth\LoginController::class, 'login']);
    Route::post('admin/logout', [Auth\LoginController::class, 'logout'])->name('admin.logout');
    Route::get('admin/login/2fa', [Auth\SocialAuthController::class, 'show_2fa_form'])->middleware('auth')->name('admin.auth.2fa');
    Route::post('admin/login/2fa', function () {
        return redirect()->route('home');
    })->middleware(['auth', 'g2fa']);
});

// }

// User Routes
Route::prefix('user')->middleware(['auth', 'user', 'verify_user'])->name('user.')->group(function () {
    Route::get('/', [UserController::class, 'index'])->name('home');
    Route::get('/account/{var}', [UserController::class, 'account'])->name('account');
    Route::get('/account/activity/activity', [UserController::class, 'account_activity'])->name('account.activity.asd');
    Route::get('/contribute', [User\TokenController::class, 'index'])->name('token');
    Route::get('/contribute/cancel/{gateway?}', [User\TokenController::class, 'payment_cancel'])->name('payment.cancel');
    Route::get('/transactions', [User\TransactionController::class, 'index'])->name('transactions');
    Route::get('/kyc', [User\KycController::class, 'index'])->name('kyc');
    Route::get('/kyc/application', [User\KycController::class, 'application'])->name('kyc.application');
    Route::get('/kyc/application/view', [User\KycController::class, 'view'])->name('kyc.application.view');
    Route::get('/kyc-list/documents/{file}/{doc}', [User\KycController::class, 'get_documents'])->name('kycs.file');
    Route::get('/password/confirm/{token}', [UserController::class, 'password_confirm'])->name('password.confirm');
    // Referral v1.0.3 > v1.1.1
    Route::get('/referral', [UserController::class, 'referral'])->name('referral');
    // My Token v1.1.2
    Route::get('/account/balance/token', [UserController::class, 'mytoken_balance'])->name('token.balance.token');

    // User Ajax Request
    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/account/wallet-form', [UserController::class, 'get_wallet_form'])->name('account.wallet');
        Route::post('/account/update', [UserController::class, 'account_update'])->name('account.update')->middleware('demo_user');
        Route::post('/contribute/access', [User\TokenController::class, 'access'])->name('token.access');
        Route::post('/contribute/payment', [User\TokenController::class, 'payment'])->name('payment');

        Route::post('/transactions/delete/{id}', [User\TransactionController::class, 'destroy'])->name('transactions.delete')->middleware('demo_user');
        Route::post('/transactions/view', [User\TransactionController::class, 'show'])->name('transactions.view');
        Route::post('/kyc/submit', [User\KycController::class, 'submit'])->name('kyc.submit');
        Route::post('/account/activity', [UserController::class, 'account_activity_delete'])->name('account.activity.delete')->middleware('demo_user');
    });
});

Route::prefix('admin')->middleware(['auth', 'admin', 'g2fa'])->name('admin.')->group(function () {
    Route::get('/', [Admin\AdminController::class, 'index'])->name('home');
    Route::any('/system-info', [Admin\AdminController::class, 'system_info'])->name('system');
    Route::any('/apps-register', [SettingController::class, 'app_register'])->name('niolite');
    Route::get('/profile', [Admin\AdminController::class, 'profile'])->name('profile');
    Route::get('/profile/activity', [Admin\AdminController::class, 'activity'])->name('profile.activity');
    Route::get('/password/confirm/{token}', [Admin\AdminController::class, 'password_confirm'])->name('password.confirm');
    Route::get('/transactions/{state?}', [Admin\TransactionController::class, 'index'])->name('transactions');
    Route::get('/check-transaction/online', [Admin\TransactionController::class, 'checkStatus'])->name('transactions.check');
    Route::get('/stages/settings', [Admin\IcoController::class, 'settings'])->name('stages.settings');
    Route::get('/pages', [Admin\PageController::class, 'index'])->name('pages');
    Route::get('/settings', [SettingController::class, 'index'])->middleware(['super_admin'])->name('settings');
    Route::get('/settings/email', [Admin\EmailSettingController::class, 'index'])->middleware(['super_admin'])->name('settings.email');
    Route::get('/settings/referral', [SettingController::class, 'referral_setting'])->middleware(['super_admin'])->name('settings.referral'); // v1.1.2
    Route::get('/settings/rest-api', [SettingController::class, 'api_setting'])->middleware(['super_admin'])->name('settings.api'); // v1.0.6
    Route::get('/payment-methods', [Admin\PaymentMethodController::class, 'index'])->middleware(['super_admin'])->name('payments.setup');
    Route::get('/payment-methods/edit/{slug}', [Admin\PaymentMethodController::class, 'edit'])->middleware(['super_admin'])->name('payments.setup.edit');
    Route::get('/stages', [Admin\IcoController::class, 'index'])->name('stages');
    Route::get('/stages/{id}', [Admin\IcoController::class, 'edit_stage'])->name('stages.edit');
    Route::get('/users/{role?}', [UsersController::class, 'index'])->name('users'); //v1.1.0
    Route::get('/users/wallet/change-request', [UsersController::class, 'wallet_change_request'])->name('users.wallet.change');
    Route::get('/kyc-list/{status?}', [Admin\KycController::class, 'index'])->name('kycs'); //v1.1.0
    Route::get('/kyc-list/documents/{file}/{doc}', [Admin\KycController::class, 'get_documents'])->name('kycs.file');
    Route::get('/transactions/view/{id}', [Admin\TransactionController::class, 'show'])->name('transactions.view');
    Route::get('/users/{id?}/{type?}', [UsersController::class, 'show'])->name('users.view');
    Route::get('/kyc/view/{id}/{type}', [Admin\KycController::class, 'show'])->name('kyc.view');
    Route::get('/pages/{slug}', [Admin\PageController::class, 'edit'])->name('pages.edit');
    Route::get('/export/{table?}/{format?}', [ExportController::class, 'export'])->middleware(['demo_user', 'super_admin'])->name('export'); // v1.1.0
    Route::get('/languages', [Admin\LanguageController::class, 'index'])->name('lang.manage'); // v1.1.3
    Route::get('/languages/translate/{code}', [Admin\LanguageController::class, 'translator'])->name('lang.translate'); // v1.1.3

    /* Regalo*/
    Route::get('/gifts/settings', [Admin\RegaloController::class, 'index'])->name('regalos.settings');
    Route::get('/gifts/{id}', [Admin\RegaloController::class, 'edit_stage'])->name('regalos.edit');
    Route::get('/users-access/{id?}/{type?}', [UsersController::class, 'Access_User'])->name('users.access');

    Route::post('/users/{id?}', [UsersController::class, 'menu'])->name('users.menu');
    /* Admin Ajax Route */
    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/users/view', [UsersController::class, 'status'])->name('users.view')->middleware('demo_user');
        Route::post('/users/showinfo', [UsersController::class, 'show'])->name('users.show');
        Route::post('/users/delete/all', [UsersController::class, 'delete_unverified_user'])->name('users.delete')->middleware('demo_user');

resources/views/admin/admin-top-referrals.blade.php
@extends('layouts.admin')
@section('gosencss')
<style>
    div.dataTables_wrapper div.dataTables_length {
        text-align: left;
    }

    div.dataTables_wrapper div.dataTables_length select {
        width: 60px;
        display: inline-block;
    }

    div.dataTables_wrapper div.dataTables_info {
        text-align: left;
        padding: 22px 0 0;


    }

    div.dataTables_wrapper div.dataTables_paginate ul.pagination {
        justify-content: flex-end;
    }

    div.dataTables_wrapper div.dataTables_filter label:before {
        position: relative;
        height: 36px;
        width: 30px;
        text-align: center;
        line-height: 36px;
        content: "\e610";
        color: #abbbd9;
        font-size: 15px;
    }

    .page-item.active .page-link {
        z-index: 3;
        color: black;
        background-color: #fff;
        border-color: black;
    }

</style>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
@endsection

@section('content')

    <div class="page-content">
        <div class="container">
            @include('layouts.messages')
            @include('vendor.notice')
            <div class="card content-area content-area-mh">
                <div class="card-innr">
                    <div class="card-head has-aside">
                        <h4 class="card-title">{{___('Top Referrarls')}}</h4>

                    </div>
                    <table id="tableID" class="data-table table-responsive-lg" style="width:100%">
                        <thead>
                            <tr class="data-item data-head">
                                <th class="data-col data-col-wd-md filter-data dt-user">#</th>
                                <th class="data-col data-col-wd-md filter-data dt-user">Id</th>
                                <th class="data-col data-col-wd-md filter-data dt-user">User</th>
                                <th class="data-col data-col-wd-md dt-referrals">{{___('Total Referrals')}}</th>
                                <th class="data-col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $Fila = 0;
                            @endphp
                            @foreach ($array as $item)
                                <tr class="data-item">
                                    <td class="data-col data-col-wd-md dt-user">
                                        {{ $Fila = $Fila + 1 }}
                                    </td>
                                    <td class="data-col data-col-wd-md dt-user">
                                        {{ $item['id'] }}
                                    </td>
                                    <td class="data-col data-col-wd-md dt-name">
                                        {{ $item['nombre'] }}
                                    </td>
                                    <td class="data-col data-col-wd-md dt-referral">
                                        {{ $item['cantidad'] }}
                                    </td>
                                    <td class="data-col text-right">
                                        <div class="card-opt data-action-list">
                                            <ul class="btn btn-auto btn-sm btn-primary">
                                                <li>
                                                    <a href="javascript:void(0)" data-uid="{{ $item['id'] }}"
                                                        data-type="referrals"
                                                        class="user-form-action user-action text-white"><em
                                                            class="fas fa-users"></em> {{___('Referrals')}}</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Initialization of datatable */
        $(document).ready(function() {
            $('#tableID').DataTable({});
        });
    </script>
@endsection

resources/views/admin/ico-stage.blade.php
@php
    use Carbon\Carbon;

    $timezone = get_setting('site_timezone', 'UTC');
    $today_date = now()->timezone($timezone);
@endphp

@extends('layouts.admin')
@section('title', 'ICO/STO Stage')

@section('content')
<div class="page-content">
    <div class="container">
        @include('vendor.notice')
        <div class="card content-area">
            <div class="card-innr">
                <div class="card-head d-flex justify-content-between align-items-center">
                    <h4 class="card-title mb-0">{{___('Available')}} ICO/STO {{___('Stage')}}</h4>
                </div>
                <div class="gaps-1-5x"></div>
                <div class="row guttar-vr-30px">
                    @forelse($stages as $stage)
                        @php
                            $start_date = Carbon::parse($stage->start_date, $timezone);
                            $end_date   = Carbon::parse($stage->end_date, $timezone);
                        @endphp
                    <div class="col-xl-4 col-md-6">
                        <div class="stage-item stage-card {{(gws('actived_stage') == $stage->id)?'stage-item-actived':'' }}">
                            <div class="stage-head">
                                <div class="stage-title">
                                    <h6>{{___('Stage Name')}} 
                                    @if($today_date->gte($start_date) && $today_date->lte($end_date) && gws('actived_stage') == $stage->id && $stage->status != 'paused')
                                    <span class="badge badge-success">{{___('Running')}}</span>
                                    @elseif($today_date->gte($start_date) && $today_date->lte($end_date) && $stage->status == 'paused')
                                    <span class="badge badge-purple">{{___('Paused')}}</span>
                                    @elseif($today_date->gte($start_date) && $today_date->lte($end_date) && $stage->status != 'paused')
                                    <span class="badge badge-secondary">{{___('Inactive')}}</span>
                                    @elseif($start_date->gt($today_date) && $today_date->lt($end_date))
                                    <span class="badge badge-warning">{{___('Upcoming')}}</span>
                                    @elseif($start_date->gt($today_date) && $today_date->lt($end_date))
                                    <span class="badge badge-info">{{___('Completed')}}</span>
                                    @else
                                    <span class="badge badge-danger">{{___('Expired')}}</span>
                                    @endif
                                    <h4>{{$stage->name}}</h4>
                                </div>
                                
                                <div class="stage-action">
                                    <a href="#" class="toggle-tigger rotate"><em class="ti ti-more-alt"></em></a>
                                    <div class="toggle-class dropdown-content dropdown-content-top-left">
                                        <ul class="dropdown-list">
                                            <li><a href="javascript:void(0);" class="stages-ajax-action" data-action="overview" data-view="modal" data-stage="{{$stage->id}}">{{___('Overview')}}</a></li>
                                            <li><a href="{{route('admin.stages.edit', $stage->id)}}">{{___('Update Stage')}}</a></li>

                                            @if(gws('actived_stage') != $stage->id)
                                            <li><form action="{{ route('admin.ajax.stages.active') }}" method="POST">
                                                @csrf
                                                <a href="javascript:void(0);" id="update_stage" data-type="active_stage" data-id="{{$stage->id}}">{{___('Make as Active')}}</a>
                                                <input class="input-bordered" type="hidden" name="actived_stage" value="{{ $stage->id }}">
                                            </form></li>
                                            @endif
                                            @if($stage->status != 'paused')
                                            <li><form action="{{ route('admin.ajax.stages.pause') }}" method="POST">
                                                @csrf
                                                <a href="javascript:void(0);" id="update_stage" data-type="pause_stage" data-id="{{$stage->id}}">{{___('Sales Pause')}}</a>
                                                <input class="input-bordered" type="hidden" name="stage_id" value="{{ $stage->id }}">
                                                <input class="input-bordered" type="hidden" name="type" value="paused">
                                            </form></li>
                                            @endif
                                            @if($stage->status == 'paused')
                                            <li><form action="{{ route('admin.ajax.stages.pause') }}" method="POST">
                                                @csrf
                                                <a href="javascript:void(0);" id="update_stage" data-type="resume_stage" data-id="{{$stage->id}}">{{___('Sales Resume')}}</a>
                                                <input class="input-bordered" type="hidden" name="stage_id" value="{{ $stage->id }}">
                                                <input class="input-bordered" type="hidden" name="type" value="active">
                                            </form></li>
                                            @endif
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="stage-info stage-info-status">
                                <div class="stage-info-graph">
                                    @if(!($start_date->gt($today_date) && $today_date->lt($end_date)))
                                    <div class="progress-pie progress-circle">
                                        <input class="knob d-none" data-thickness=".125" data-width="100%" data-fgColor="#2b56f5" data-bgColor="#c8d2e5" value="{{ to_percent($stage->soldout, $stage->total_tokens) }}">
                                        <div class="progress-txt"><span class="progress-amount">{{ to_percent($stage->soldout, $stage->total_tokens) }}</span>% <span class="progress-status">{{___('Sold')}}</span></div>
                                    </div>
                                    @else
                                    <div class="progress-soon progress-circle">
                                        <div class="progress-txt"><span class="progress-status">{{___('Coming Soon')}}</span></div>
                                    </div>
                                    @endif
                                </div>
                                <div class="stage-info-txt">
                                    <h6>Token Issued</h6>
                                    <span class="stage-info-total h4">{{ to_num_token($stage->total_tokens, 0) }}</span>
                                    <div class="stage-info-count">{{___('Sold')}} <span>{{ to_num_token($stage->soldout, 0) }}</span> {{___('Tokens')}}</div>
                                </div>
                            </div>
                            <div class="stage-info">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="stage-info-txt">
                                            <h6>{{___('Base Price')}}</h6>
                                            <div class="h2 stage-info-number">{{ to_num($stage->base_price, 'max') }}<small>{{ base_currency(true) }}</small></div>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="stage-info-txt">
                                            <h6>{{___('Base Bonus')}}</h6>  
                                            <div class="h2 stage-info-number">{{ stage_meta($stage->id) }}<small>%</small></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="stage-date">
                                <div class="row">
                                    <div class="col-6">
                                        <h6>{{___('Start Date')}}</h6>
                                        <h5>{{ _date2sz($stage->start_date, gws('site_date_format')) }} <br><small>{{ _date2sz($stage->start_date, gws('site_time_format')) }}</small></h5>
                                    </div>
                                    <div class="col-6">
                                        <h6>{{___('End Date')}}</h6>
                                        <h5>{{ _date2sz($stage->end_date, gws('site_date_format')) }} <br><small>{{ _date2sz($stage->end_date, gws('site_time_format')) }}</small></h5>
                                    </div>
                                </div>
                            </div>
                        </div>{{-- .stage-card --}}
                    </div>{{-- .col --}}
                    @empty
                    <span>{{___('No Stage Found')}}</span>
                    @endforelse

                </div>
                <div class="gaps-0-5x"></div>
            </div>
        </div>
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

resources/views/admin/language-translate-intro.blade.php
@extends('layouts.admin')
@section('title', ___('Translate Language'))
@push('header')
<style type="text/css">
    .sidebar-nav li.active>a {font-weight: bold;}
</style>
@endpush
@section('content')
<div class="page-content">
    <div class="container">
        @include('vendor.notice')
        <div class="row">
            <div class="col-lg-3 aside sidebar-left">
                <div class="card card-navs">
                    <div class="card-innr">
                        <div class="card-head d-none d-lg-block">
                            <h6 class="card-title card-title-md">{{ ___(':lang Translation', ['lang' => $lang->name]) }}</h6>
                        </div>
                        <ul class="sidebar-nav">
                            <li><a href="{{ url()->current() }}"><em class="ikon ikon-dashboard"></em> {{___('Instruction')}}</a></li>
                            @foreach($tags as $name => $term )
                            <li{!! (url()->full() == qs_url(['category' => $term, 'filter' => true], url()->current())) ? ' class="active"' : '' !!}><a href="{{ qs_url(['category' => $term, 'filter' => true], url()->current()) }}"><em class="ikon ikon-transactions"></em> {{ $name }}</a></li>
                            @endforeach
                            <li{!! (url()->full() == qs_url(['filter' => true], url()->current())) ? ' class="active"' : '' !!}><a href="{{ qs_url(['filter' => true], url()->current()) }}"><em class="ikon ikon-docs"></em> {{___('All Translation')}}</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content col-lg-9">
                <div class="content-area card">
                    <div class="card-innr">
                        <div class="card-head has-aside">
                            <h4 class="card-title">
                                @if( request()->filter )
                                {{ ___(':page Translation', ['page' => $lang->name]) }}
                                @else
                                {{ ___('Instruction for Translation') }}
                                @endif
                            </h4>
                            <div class="card-opt">
                                <ul class="btn-grp btn-grp-block guttar-20px">
                                    <li><a href="{{ route('admin.lang.manage') }}" class="btn btn-auto btn-sm btn-primary"><em class="fas fa-arrow-left"></em><span class="d-sm-inline-block d-none">Back</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="gaps-1-5x"></div>
                        <div class="card-text">
                            <p><strong>{{___('You can easily translate')}}<strong>{{___('Base')}}</strong> {{___('text to')}} <strong>{{ $lang->name }}</strong>. {{___('When you update please keep in mind few thing as below referrence')}}.</p>
                            <ul class="list list-check">
                                <li>{{___('Once you change or update any text then must re-genarate the language file from Manage Languages page')}}</li>
                                <li>{{___('Ensure that your 'resource/lang' folder have write permission')}}.</li>
                                <li>{{___('On Leftside you have all type text, you navigate and update if you need')}}.</li>
                                <li><p><strong>{{___('Important')}}:</strong> {{___('If any where have')}} '<span class="badge-lighter"> :TOKEN </span>', '<span class="badge-lighter"> :{{___('symbol')}} </span>', '<span class="badge-lighter"> :{{___('currency')}} </span>', '<span class="badge-lighter"> :{{___('amount')}} </span>' {{___('or something like which is start with')}} '<span class="badge-light"> : </span>' {{___('clone without space, please keep and use same as this is consider as variable & dynamically populate')}}.</p></li>
                                <li><p>{{___('Example as below')}}.<br><strong>{{___('Base')}}:</strong> {{___('Choose currency and calculate :SYMBOL')}} token {{___('price')}}.</p>
                                    <p><strong>French:</strong> Choisissez la devise et calculez le prix du jeton :SYMBOL.</p>
                                    <p><strong>Turkish:</strong> Para birimini seçin ve :SYMBOL token fiyatını hesaplayın.</p>
                                </li>
                            </ul>
                            <h5 class="font-mid">{{___('DO or DONT')}}</h5>
                            <p>
                                <em class="fa fa-check-circle text-success"></em> {{___('Use exactly what shown in Base text')}} <span class="badge-lighter"> :SYMBOL </span> &nbsp;or <span class="badge-lighter"> :symbol </span><br>
                                <em class="fa fa-times-circle text-danger"></em> {{___('Do not use as')}} <span class="badge-lighter"> SYMBOL: </span> &nbsp; (: {{___('colon after word')}}) <br>
                                <em class="fa fa-times-circle text-danger"></em> {{___('Do not switch case')}} <span class="badge-lighter"> :SYMBOL </span> &nbsp;to <span class="badge-lighter"> :symbol </span> &nbsp; or &nbsp; <span class="badge-lighter"> :symbol </span> to <span class="badge-lighter"> :SYMBOL </span>
                            </p>
                            <div class="gaps-1x"></div>
                            <p><strong>{{___('If you need any help or face problem please feel free to')}} <a target="_blank" href="https://softnio.com/contact/">{{___('contact us')}}</a>.</strong></p>
                        </div>
                    </div>{{-- .card-innr --}}
                </div>{{-- .card --}}
            </div>{{-- .col --}}
        </div>{{-- .row --}}
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

@push('footer')
<script type="text/javascript">
    (function($){
        var $translation = $(".lang-translation");
        if ($translation.length > 0) { ajax_form_submit($translation, false); }
    })(jQuery);
</script>
@endpush